import { FormEvent, useEffect, useMemo, useState } from 'react'
import { loadPublicCourseProfiles, loadPublicLearningPaths, type PublicCourseProfileAdmin, type PublicLearningPathAdmin } from '../services/publicPortalAdminApi'
import { changePlanPrice, createPlan, createPlanPrice, loadPlans, loadSubscriptions, savePlan, type PlanAdmin } from '../services/plansApi'
import '../styles/plans-admin.css'

function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,120)}
function parseBenefits(value:string){return value.split('\n').map((line)=>line.trim()).filter(Boolean).map((line)=>{const [sourceSystem,externalRef,label,...rest]=line.split('|').map((item)=>item.trim());return{sourceSystem,externalRef,label,description:rest.join(' | ')}}).filter((item)=>item.sourceSystem&&item.externalRef&&item.label)}
function formatMoney(cents:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100)}

const emptyForm={name:'',slug:'',description:'',audienceType:'individual' as PlanAdmin['audienceType'],commercialMode:'priced' as PlanAdmin['commercialMode'],status:'draft' as PlanAdmin['status'],featured:false,maxUsers:'',seoTitle:'',seoDescription:'',courseIds:[] as string[],pathIds:[] as string[],benefits:''}

export function PlansGovernancePage(){
  const [plans,setPlans]=useState<PlanAdmin[]>([]);const [courses,setCourses]=useState<PublicCourseProfileAdmin[]>([]);const [paths,setPaths]=useState<PublicLearningPathAdmin[]>([]);const [selectedId,setSelectedId]=useState('new');const [message,setMessage]=useState('');const [form,setForm]=useState(emptyForm);const [price,setPrice]=useState({billingInterval:'monthly' as 'monthly'|'annual',priceUnit:'subscription' as 'subscription'|'per_user',amount:'',activate:true});const [subscriptionCount,setSubscriptionCount]=useState(0)
  const selected=useMemo(()=>plans.find((item)=>item.id===selectedId)??null,[plans,selectedId])
  const eligibleCourses=useMemo(()=>courses.filter((item)=>item.courseStatus==='published'&&item.visibility==='public'),[courses]);const eligiblePaths=useMemo(()=>paths.filter((item)=>item.visibility==='public'),[paths])

  async function refresh(){try{const [planData,courseData,pathData,subs]=await Promise.all([loadPlans(),loadPublicCourseProfiles(),loadPublicLearningPaths(),loadSubscriptions()]);setPlans(planData);setCourses(courseData);setPaths(pathData);setSubscriptionCount(subs.data.length)}catch(error){setMessage(error instanceof Error?error.message:'Falha ao carregar planos.')}}
  useEffect(()=>{void refresh()},[])
  useEffect(()=>{if(!selected){setForm(emptyForm);return}setForm({name:selected.name,slug:selected.slug,description:selected.description,audienceType:selected.audienceType,commercialMode:selected.commercialMode,status:selected.status,featured:selected.featured,maxUsers:selected.maxUsers==null?'':String(selected.maxUsers),seoTitle:selected.seoTitle||'',seoDescription:selected.seoDescription||'',courseIds:selected.courses.map((item)=>item.courseId),pathIds:selected.paths.map((item)=>item.pathId),benefits:selected.externalBenefits.map((item)=>`${item.sourceSystem}|${item.externalRef}|${item.label}|${item.description}`).join('\n')})},[selectedId,selected?.updatedAt])

  function toggle(list:'courseIds'|'pathIds',id:string){setForm((current)=>({...current,[list]:current[list].includes(id)?current[list].filter((item)=>item!==id):[...current[list],id]}))}
  async function submit(event:FormEvent){event.preventDefault();try{if(!selected){await createPlan({slug:form.slug||slugify(form.name),name:form.name,description:form.description,audienceType:form.audienceType,commercialMode:form.commercialMode,featured:form.featured,maxUsers:form.maxUsers?Number(form.maxUsers):null,seoTitle:form.seoTitle||null,seoDescription:form.seoDescription||null});setMessage('Plano criado como draft. Configure benefícios e preço antes de publicar.');setSelectedId('new')}else{await savePlan({planId:selected.id,slug:form.slug,name:form.name,description:form.description,audienceType:form.audienceType,commercialMode:form.commercialMode,status:form.status,featured:form.featured,maxUsers:form.maxUsers?Number(form.maxUsers):null,seoTitle:form.seoTitle||null,seoDescription:form.seoDescription||null,courseIds:form.courseIds,pathIds:form.pathIds,externalBenefits:parseBenefits(form.benefits)});setMessage('Plano atualizado com governança de publicação.')}await refresh()}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar plano.')}}
  async function addPrice(event:FormEvent){event.preventDefault();if(!selected)return;const amount=Number(price.amount.replace(',','.'));if(!Number.isFinite(amount)||amount<=0){setMessage('Informe um preço válido.');return}try{await createPlanPrice({planId:selected.id,billingInterval:price.billingInterval,priceUnit:price.priceUnit,amountCents:Math.round(amount*100),activate:price.activate});setPrice({...price,amount:''});await refresh();setMessage('Nova versão de preço criada.')}catch(error){setMessage(error instanceof Error?error.message:'Falha ao criar preço.')}}
  async function priceAction(priceId:string,action:'activate'|'retire'){try{await changePlanPrice(priceId,action);await refresh();setMessage(action==='activate'?'Preço ativado; versão anterior foi aposentada.':'Preço aposentado.')}catch(error){setMessage(error instanceof Error?error.message:'Falha ao alterar preço.')}}

  return <div className="plansAdmin"><div className="pageHeader"><div><h1>Planos & Ofertas</h1><p>Planos individuais, corporativos e parceiros com preços versionados e benefícios do ecossistema por referência.</p>{message&&<small>{message}</small>}</div><div className="headerActions"><button onClick={()=>window.open('/plans','_blank','noopener,noreferrer')}>Ver planos públicos</button><button onClick={()=>setSelectedId('new')}>Novo plano</button></div></div>
    <section className="plansMetrics"><article><span>Planos</span><strong>{plans.length}</strong></article><article><span>Públicos</span><strong>{plans.filter((item)=>item.status==='public').length}</strong></article><article><span>Preços ativos</span><strong>{plans.flatMap((item)=>item.prices).filter((item)=>item.status==='active').length}</strong></article><article><span>Assinaturas registradas</span><strong>{subscriptionCount}</strong><small>somente leitura na v0.41</small></article></section>
    <section className="plansLayout"><aside className="panel planList"><button className={selectedId==='new'?'active':''} onClick={()=>setSelectedId('new')}><strong>Novo plano</strong><span>Criado sempre como draft</span></button>{plans.map((plan)=><button key={plan.id} className={selectedId===plan.id?'active':''} onClick={()=>setSelectedId(plan.id)}><strong>{plan.name}</strong><span>{plan.status} · {plan.commercialMode}</span></button>)}</aside>
      <div className="planEditor"><form className="panel planForm" onSubmit={submit}><div className="panelTitle"><div><h2>{selected?selected.name:'Novo plano'}</h2><span>{selected?'Edição segura: volta a draft antes de republicar.':'Defina a base comercial; nenhum preço padrão será criado.'}</span></div></div><div className="planFormGrid"><label>Nome<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value,slug:selected?form.slug:slugify(e.target.value)})}/></label><label>Slug<input required value={form.slug} onChange={(e)=>setForm({...form,slug:e.target.value.toLowerCase()})}/></label><label>Público<select value={form.audienceType} onChange={(e)=>setForm({...form,audienceType:e.target.value as PlanAdmin['audienceType'],maxUsers:e.target.value==='corporate'?form.maxUsers:''})}><option value="individual">Individual</option><option value="corporate">Corporativo</option><option value="partner">Parceiro</option></select></label><label>Modelo comercial<select value={form.commercialMode} onChange={(e)=>setForm({...form,commercialMode:e.target.value as PlanAdmin['commercialMode']})}><option value="free">Gratuito</option><option value="priced">Preço configurado</option><option value="contact_sales">Fale com vendas</option></select></label>{form.audienceType==='corporate'&&<label>Máx. usuários<input type="number" min="1" value={form.maxUsers} onChange={(e)=>setForm({...form,maxUsers:e.target.value})}/></label>}{selected&&<label>Status<select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as PlanAdmin['status']})}><option value="draft">Draft</option><option value="public">Público</option><option value="archived">Arquivado</option></select></label>}</div><label>Descrição<textarea value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label>
        {selected&&<><div className="planPickers"><div><strong>Cursos públicos</strong>{eligibleCourses.map((item)=><label key={item.courseId}><input type="checkbox" checked={form.courseIds.includes(item.courseId)} onChange={()=>toggle('courseIds',item.courseId)}/>{item.courseTitle}</label>)}</div><div><strong>Trilhas públicas</strong>{eligiblePaths.map((item)=><label key={item.id}><input type="checkbox" checked={form.pathIds.includes(item.id)} onChange={()=>toggle('pathIds',item.id)}/>{item.title}</label>)}</div></div><label>Benefícios externos — uma linha por referência<textarea placeholder="ifarm_store|SKU-123|Kit de sensores|Condição vinculada ao plano" value={form.benefits} onChange={(e)=>setForm({...form,benefits:e.target.value})}/><small>Formato: sistema|referência|rótulo|descrição. A Academy não replica produto/estoque/contrato.</small></label></>}
        <div className="planFormGrid"><label>Título SEO<input maxLength={160} value={form.seoTitle} onChange={(e)=>setForm({...form,seoTitle:e.target.value})}/></label><label>Descrição SEO<input maxLength={320} value={form.seoDescription} onChange={(e)=>setForm({...form,seoDescription:e.target.value})}/></label></div><label className="portalCheck"><input type="checkbox" checked={form.featured} onChange={(e)=>setForm({...form,featured:e.target.checked})}/> Destacar plano</label>{selected&&form.status==='public'&&form.commercialMode==='priced'&&!selected.prices.some((item)=>item.status==='active')&&<p className="portalWarning">Plano priced público exige preço ativo.</p>}<button className="primary">{selected?'Salvar plano':'Criar draft'}</button></form>
        {selected&&selected.commercialMode==='priced'&&<section className="panel pricePanel"><div className="panelTitle"><div><h2>Preços versionados</h2><span>Nunca sobrescrever uma condição histórica.</span></div></div><form className="priceCreate" onSubmit={addPrice}><select value={price.billingInterval} onChange={(e)=>setPrice({...price,billingInterval:e.target.value as 'monthly'|'annual'})}><option value="monthly">Mensal</option><option value="annual">Anual</option></select><select value={price.priceUnit} onChange={(e)=>setPrice({...price,priceUnit:e.target.value as 'subscription'|'per_user'})}><option value="subscription">Por assinatura</option><option value="per_user">Por usuário</option></select><input required type="number" min="0.01" step="0.01" placeholder="R$" value={price.amount} onChange={(e)=>setPrice({...price,amount:e.target.value})}/><label><input type="checkbox" checked={price.activate} onChange={(e)=>setPrice({...price,activate:e.target.checked})}/> ativar agora</label><button>Criar nova versão</button></form><div className="priceHistory">{selected.prices.map((item)=><article key={item.id}><div><strong>{formatMoney(item.amountCents)}</strong><span>{item.billingInterval} · {item.priceUnit} · v{item.version} · {item.status}</span></div><div>{item.status==='draft'&&<button onClick={()=>void priceAction(item.id,'activate')}>Ativar</button>}{item.status!=='retired'&&<button onClick={()=>void priceAction(item.id,'retire')}>Aposentar</button>}</div></article>)}{!selected.prices.length&&<p>Nenhum preço criado.</p>}</div></section>}
        {selected&&<section className="panel subscriptionGuard"><strong>Assinaturas: escrita bloqueada na v0.41</strong><p>O painel só consulta registros. Ativação paga exigirá confirmação real do provedor; ativação gratuita/contratual exigirá referência explícita homologada.</p></section>}
      </div></section></div>
}
