import { useEffect, useState, type CSSProperties } from 'react'
import { ContextualRecommendations } from '../components/ContextualRecommendations'
import {
  formatBundlePrice, loadPublicBundle, loadPublicBundles, loadPublicPartner, loadPublicPartners,
  type PublicBundleDetail, type PublicBundleSummary, type PublicPartner, type PublicPartnerDetail,
} from '../services/partnersBundlesApi'
import type { PublicBrand } from '../services/publicPortalApi'
import '../styles/public-partners-bundles.css'

const defaultBrand:PublicBrand={brandName:'iFarm',academyName:'iFarm Academy',primaryColor:'#004E3B',secondaryColor:'#087A51',accentColor:'#00825B',whiteLabelConfigured:false}
function style(brand:PublicBrand):CSSProperties{return {'--portal-primary':brand.primaryColor,'--portal-secondary':brand.secondaryColor,'--portal-accent':brand.accentColor} as CSSProperties}
function go(path:string){window.location.assign(path)}
function header(brand:PublicBrand){return <header className="pbHeader"><button className="pbBrand" onClick={()=>go('/')}><span>{brand.logoRef?<img src={brand.logoRef} alt=""/>:'iF'}</span><div><strong>{brand.brandName}</strong><small>{brand.academyName}</small></div></button><nav><button onClick={()=>go('/search')}>Buscar</button><button onClick={()=>go('/courses')}>Cursos</button><button onClick={()=>go('/paths')}>Trilhas</button><button onClick={()=>go('/bundles')}>Bundles</button><button onClick={()=>go('/partners')}>Parceiros</button><button className="pbLogin" onClick={()=>go('/app')}>Entrar</button></nav></header>}

function BundleCard({bundle}:{bundle:PublicBundleSummary}){return <article className="pbBundleCard"><div className="pbBundleCover">{bundle.coverRef?<img src={bundle.coverRef} alt=""/>:<span>Bundle iFarm</span>}</div><div className="pbBundleBody"><div className="pbBadges"><span>Bundle</span>{bundle.featured&&<span>Destaque</span>}</div><h2>{bundle.title}</h2><p>{bundle.description}</p><div className="pbBundleBottom"><div><strong>{formatBundlePrice(bundle)}</strong>{bundle.itemCount!=null&&<small>{bundle.itemCount} itens públicos</small>}</div><button onClick={()=>go(`/bundles/${bundle.slug}`)}>Ver bundle</button></div></div></article>}
function PartnerCard({partner}:{partner:PublicPartner}){return <article className="pbPartnerCard"><div className="pbPartnerLogo">{partner.logoRef?<img src={partner.logoRef} alt=""/>:<span>{partner.displayName.slice(0,2).toUpperCase()}</span>}</div><div><div className="pbBadges"><span>{partner.partnerType}</span>{partner.featured&&<span>Destaque</span>}</div><h2>{partner.displayName}</h2><p>{partner.description}</p><button onClick={()=>go(`/partners/${partner.slug}`)}>Conhecer parceiro</button></div></article>}

function BundleDetailView({data}:{data:PublicBundleDetail}){
  const itemTotal=data.courses.length+data.paths.length+data.plans.length+data.externalItems.length
  return <main className="pbMain"><section className="pbDetailHero"><div><small>Bundle iFarm Academy</small><h1>{data.title}</h1><p>{data.description}</p><div className="pbBadges"><span>{itemTotal} itens disponíveis</span>{data.partners.length>0&&<span>{data.partners.length} parceiros</span>}</div></div><aside><small>Condição</small><strong>{formatBundlePrice(data)}</strong><button onClick={()=>go('/app')}>{data.commercialMode==='free'?'Entrar para acessar':'Entrar para acompanhar'}</button><p>Checkout e entitlement só serão ativados após homologação da camada comercial.</p></aside></section><ContextualRecommendations surface="bundle" contextRef={data.id}/>
    <section className="pbSection"><h2>O que está incluído</h2><div className="pbItemGrid">{data.courses.map(x=><article key={`c-${x.id}`}><span>Curso</span><strong>{x.title}</strong>{x.category&&<small>{x.category}</small>}<button onClick={()=>go(`/courses/${x.slug}`)}>Ver curso</button></article>)}{data.paths.map(x=><article key={`p-${x.id}`}><span>Trilha</span><strong>{x.title}</strong><small>{x.description}</small><button onClick={()=>go(`/paths/${x.slug}`)}>Ver trilha</button></article>)}{data.plans.map(x=><article key={`pl-${x.id}`}><span>Plano</span><strong>{x.title}</strong><small>{x.description}</small><button onClick={()=>go(`/plans/${x.slug}`)}>Ver plano</button></article>)}{data.externalItems.map((x,i)=><article key={`e-${x.sourceSystem}-${i}`}><span>{x.itemType}</span><strong>{x.label}</strong><small>{x.description}</small><em>Origem: {x.sourceSystem}</em></article>)}</div></section>
    {data.partners.length>0&&<section className="pbSection"><h2>Parceiros envolvidos</h2><div className="pbPartnerStrip">{data.partners.map(x=><button key={x.id} onClick={()=>go(`/partners/${x.slug}`)}>{x.logoRef&&<img src={x.logoRef} alt=""/>}<span><strong>{x.displayName}</strong><small>{x.partnerType}</small></span></button>)}</div></section>}
    <section className="pbNotice"><strong>Composição por referência</strong><p>Produtos, serviços, financiamento, seguros ou benefícios externos continuam pertencendo aos módulos responsáveis do ecossistema iFarm. A Academy não duplica estoque, contrato, apólice ou cadastro financeiro.</p></section>
  </main>
}

function PartnerDetailView({data}:{data:PublicPartnerDetail}){return <main className="pbMain"><section className="pbPartnerHero"><div className="pbPartnerLogo large">{data.logoRef?<img src={data.logoRef} alt=""/>:<span>{data.displayName.slice(0,2).toUpperCase()}</span>}</div><div><small>Parceiro · {data.partnerType}</small><h1>{data.displayName}</h1><p>{data.description}</p>{data.websiteUrl&&<a href={data.websiteUrl} target="_blank" rel="noopener noreferrer">Site oficial do parceiro</a>}</div></section><ContextualRecommendations surface="partner" contextRef={data.id}/>{data.bundles.length>0&&<section className="pbSection"><h2>Bundles com este parceiro</h2><div className="pbBundleGrid">{data.bundles.map(x=><BundleCard key={x.id} bundle={x}/>)}</div></section>}<section className="pbNotice"><strong>Perfil público</strong><p>Esta página é uma projeção editorial da parceria. O cadastro mestre, contratos e dados privados permanecem no sistema de origem referenciado.</p></section></main>}

export function PublicPartnersBundlesPage(){
  const pathname=window.location.pathname
  const partnerMatch=pathname.match(/^\/partners\/([a-z0-9-]+)$/); const bundleMatch=pathname.match(/^\/bundles\/([a-z0-9-]+)$/)
  const mode=partnerMatch?'partner':bundleMatch?'bundle':pathname==='/partners'?'partners':'bundles'
  const [brand,setBrand]=useState(defaultBrand); const [partners,setPartners]=useState<PublicPartner[]>([]); const [bundles,setBundles]=useState<PublicBundleSummary[]>([])
  const [partner,setPartner]=useState<PublicPartnerDetail|null>(null); const [bundle,setBundle]=useState<PublicBundleDetail|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{let cancelled=false;setLoading(true);setError('');const run=async()=>{if(mode==='partners'){const r=await loadPublicPartners();if(!cancelled){setBrand(r.brand);setPartners(r.data)}}else if(mode==='partner'&&partnerMatch){const r=await loadPublicPartner(partnerMatch[1]);if(!cancelled){setBrand(r.brand);setPartner(r.data)}}else if(mode==='bundle'&&bundleMatch){const r=await loadPublicBundle(bundleMatch[1]);if(!cancelled){setBrand(r.brand);setBundle(r.data)}}else{const r=await loadPublicBundles();if(!cancelled){setBrand(r.brand);setBundles(r.data)}}};void run().catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Portal indisponível')}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[pathname])
  return <div className="pbPage" style={style(brand)}>{header(brand)}{loading&&<main className="pbState">Carregando...</main>}{!loading&&error&&<main className="pbState error"><h1>Conteúdo indisponível</h1><p>{error}</p><button onClick={()=>go('/')}>Voltar ao portal</button></main>}{!loading&&!error&&mode==='partners'&&<main className="pbMain"><section className="pbHeading"><small>Ecossistema</small><h1>Parceiros</h1><p>Empresas e instituições conectadas à educação, tecnologia e serviços da iFarm Academy.</p></section><div className="pbPartnerGrid">{partners.map(x=><PartnerCard key={x.id} partner={x}/>)}</div>{!partners.length&&<div className="pbState">Nenhum parceiro público configurado.</div>}</main>}{!loading&&!error&&mode==='bundles'&&<main className="pbMain"><section className="pbHeading"><small>Ofertas integradas</small><h1>Bundles</h1><p>Combinações educacionais com cursos, trilhas, planos e referências a produtos ou serviços do ecossistema.</p></section><div className="pbBundleGrid">{bundles.map(x=><BundleCard key={x.id} bundle={x}/>)}</div>{!bundles.length&&<div className="pbState">Nenhum bundle público configurado.</div>}</main>}{!loading&&!error&&partner&&<PartnerDetailView data={partner}/>} {!loading&&!error&&bundle&&<BundleDetailView data={bundle}/>}<footer className="pbFooter"><strong>{brand.academyName}</strong><span>Educação conectada ao ecossistema iFarm.</span></footer></div>
}
